name: Publish to nuget

on:
  push:
    branches:
      - main
    paths:
      - src/version.props
      - .github/workflows/nuget.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Publish NuGet
        uses: likvido/action-nuget@v1
        with:
          nuget-key: ${{ secrets.NUGET_API_KEY }}
          project: src/Likvido.Identity/Likvido.Identity.csproj
